version: '3'
services:

  db:
    image: mysql:8.0.36
    container_name: db
    env_file:
      - .env
    ports:
      - "3000:3306"
    restart: always

  msa-member:
    image: jekim12/msa-member
    build:
      context: ./msa-member/msa-member
      dockerfile: Dockerfile
    container_name: msa-member
    volumes:
      - /tmp/msa-member/gradle-cache:/home/gradle/.gradle
      - ./msa-member/msa-member/src:/usr/src/app/src:z
    ports:
      - "3001:8080"
    environment:
      - PORT = 8080
      - NODE_ENV=development
    restart: "no"

  msa-front:
    image: jekim12/msa-front
    build:
      context: ./msa-front
      dockerfile: Dockerfile
    container_name: msa-front
    volumes:
      - /tmp/msa-front/npm-cache:/root/.npm
      - ./msa-front/src:/usr/src/app/src:z
    ports:
      - "3002:3000"
    environment:
      - PORT = 3000
      - NODE_ENV=development
    restart: "no"
