# msa-portfolio Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: msa-portfolio
  template:
    metadata:
      labels:
        app: msa-portfolio
    spec:
      containers: 
      - name: msa-portfolio
        image: julia2039/msa-portfolio:v7
        ports:
          - containerPort: 8080
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: url
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
