# msa-crawling-univ CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: msa-crawling-univ
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: msa-crawling-univ
            image: hyezis/msa-crawling-univ:latest
            env:
            - name: RABBITMQ_HOST
              value: msa-rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred